version: "3"
name: dispenser


volumes:
  pg-data:


services:
  db:
    image: postgres:latest
    volumes:
      - pg-data:/var/lib/postgresql/data
    ports:
      - "5454:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dispenser -d dispenser"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_DB: dispenser
      POSTGRES_USER: dispenser
      POSTGRES_PASSWORD: dispenser
