classDiagram

Servo "1" o-- "1" DispencerDriver
DispencerDriver "1" o-- "1" DispencerSequence

class DispencerDriver {
    -Servo* pMotor
    -int initAngle
    -int angle[2]

    +void dispence(int)
}

class DispencerSequence{
    -int sequence[32]
    -int seqLen
    -DispencerDriver* motorDriver

    +int dispence()
    +void pushToSeq(int)
    +bool checkSeq()
}

class Servo{
    +int servoPin

    +void attach(int)
    +void write(int)
}
